### ISSUE TITLE
A lot of "The Micro Dot pHAT" files...

### ISSUE THREAD

**Issue by dglaude** [pimoroni/mote#1]
Apparently a lot of files for "The Micro Dot pHAT" are mixed into the mote stuff...

**Comment by RogueM** [comment]
This repo is WIP, we are in the process of sorting things out - please hold your fire until at least Monday before filling issues ;-)

**Comment by Gadgetoid** [comment]
This is, indeed, WIP, I made it public for internal convenience ;) I did a lot of copypasta to get the boilerplate stuff in place.
