### ISSUE TITLE
Cheerlights Example Python 3

### ISSUE THREAD

**Issue by Tom-Archer** [pimoroni/mote#13]
Ran into a slight issue getting cheerlights running using Python 3.

I got the error: 'str' object has no attribute 'decode'

Which is down to this line:

```r, g, b = tuple(ord(c) for c in col[1:].lower().decode('hex'))```

Replacing it with this got it working:

```r, g, b = tuple(c for c in bytes.fromhex(col[1:]))```

But I can't vouch for Python 2.

**Comment by Gadgetoid** [comment]
Have now merged and modified your fix, thank you.

I've also borrowed it for Blinkt! where it makes a nice succinct substitute to the somewhat bloaty solution I'd arrived at:

https://github.com/pimoroni/blinkt/commit/2722d832358ef27d5afce2c8b0825034ff06c4ae
