### ISSUE TITLE
Handling of timeout on USB serial writes

### ISSUE THREAD

**Issue by PaulWebster** [pimoroni/mote#24]
I just ran into an odd problem.
I updated my RPi that runs OSMC (Feb 2018 release) and the lights started to play up.
After a few minutes they stopped updating.
I found that the problem was that python was stalling in my call to
mote.show()

After further debugging I could see that it was getting stuck in "show" waiting for a USB Serial write to complete.
Below is what I did to get around this - but I can't post it as a patch because my "0.3" is not the same as yours (mine came from the Mote Stick example). Anyway the code is broadly the same in the problem area.

I put a try/except around the port.write calls. I did it only in the section that writes out the LED data but I suppose similar should be in the part that does the configuration (higher up in the code ... don't just copy paste there though because it sends a "c" and you might want to raise an exception and fail in that one).

`        try:
            self.port.write(b'mote')
            self.port.write(b'o')
            self.port.write(buf)
        except serial.SerialTimeoutException:
            # Unexpected timeout when writing to device ... try to ignore and carry on
            self.port.flushOutput()
            # print("Mote - Had serial timeout")
`

To make it possible for the timeout to happen I added a parameter to the port initialisation call - write_timeout

`self.port = serial.Serial(self.port_name, 115200, timeout=1, write_timeout=0.5)`

**Comment by Gadgetoid** [comment]
This is curious. Thank you for your suggestions. Any idea why it times out in the first place? Do you see any useful USB debugging information in "dmesg"?

**Comment by PaulWebster** [comment]
There was nothing in dmesg.
Coincided with update of OSMC - so perhaps new RPi boot files or revised USB drivers.
Have run it for 2 hours with the updates and did not get frozen lights at all.
If the timeout never happens then the new code is not executed anyway - so a relatively safe change.
