### ISSUE TITLE
set_all doesn't work at all

### ISSUE THREAD

**Issue by veryalien** [pimoroni/mote#26]
I was converting some ledshim code to mote and got errors with trying to call set_all after installing the mote master branch.
NUM_CHANNELS isn't defined, I defined it with the value 4
NUM_PIXELS_PER_CHANNEL isn't defined, I  defined it with the value 16
set_pixel can't be called within set_all because self is missing as the first parameter in the set_all definition.
Sometimes you really begin to wonder....

**Comment by veryalien** [comment]
I see what you did now, it's a copy of the set_all code from mote-phat. But it doesn't work like that here.

**Comment by Gadgetoid** [comment]
Whoa, I really did make a pig's ear of this. I'll suspect it's because I somehow never seem to have a Mote kit on hand to test anything. Groan. Thanks for diagnosing.

**Comment by Gadgetoid** [comment]
Should be fixed in release v0.0.4, along with some other tweaks for feature parity with the Mote pHAT library.
