### ISSUE TITLE
mote-api example - state error

### ISSUE THREAD

**Issue by bakman2** [pimoroni/mote#29]
Trying to use `mote-api` 
I get errors when retrieving status of the lights

`curl -i http://10.0.0.35:5555/mote/api/v1.0/channel/all/state`

```
   br = rgb_to_hsv(*col)[2]
TypeError: rgb_to_hsv() takes 3 positional arguments but 4 were given
```

https://github.com/pimoroni/mote/blob/cee95377e94aec084d12e3d1b0db905e9d52a3a8/python/examples/mote-api.py#L72

Setting the state,  colors, brightness do work

**Comment by bakman2** [comment]
I am not into python (just yet), changing it to:

` br = rgb_to_hsv(col[0],col[1],col[2])`

Seems to work, but then `state/on` doesn't work.
Is the `*col` something specific for a python version ?

**Comment by Gadgetoid** [comment]
The `*` is the splat/spread operator called "unpack" in Python I believe.

It will take a tuple/list such as `col` in this case, and convert it into positional arguments to be passed into the function.

So:

```
rgb_to_hsv(*col)
```

Is equivilent to:

```
rgb_to_hsv(col[0], col[1], col[2])
```

But only if col has just 3 elements.

In this case it looks like the underlying library was updated here: https://github.com/pimoroni/mote/commit/d6ee9b14fa47e4d9fe808f65e832162ebfdbd137#diff-3e874a60bc83ae648b90f50440252558

Which changed it to return 4 elements: https://github.com/pimoroni/mote/commit/d6ee9b14fa47e4d9fe808f65e832162ebfdbd137#diff-3e874a60bc83ae648b90f50440252558R81

Thus breaking the use of `*`.

This extra parameter probably breaks other things, so it makes sense to deal with it in `get_state()` replacing:

```
        col = mote.get_pixel(chan, 0)
        br = rgb_to_hsv(*col)[2]
        status['colour'][chan] = list(col)
        status['brightness'][chan] = br
```

with something like:

```
        r, g, b, a = mote.get_pixel(chan, 0)
        br = rgb_to_hsv(r, g, b)[2]
        status['colour'][chan] = list(r, g, b)
        status['brightness'][chan] = br
```

Keen to know if this works for you- I don't have a Mote to hand to quickly test it right now.

**Comment by bakman2** [comment]
@Gadgetoid thanks a lot!

It works with a small modification:

```
 r, g, b, a = mote.get_pixel(chan, 0)
        br = rgb_to_hsv(r, g, b)[2]
        status['colour'][chan] = list([r, g, b])
        status['brightness'][chan] = br
```

(list should have an argument of 1)

I want to add an api option to control a specific led number on the strip, per channel.
